### PR TITLE
Feat: CTRL+S to save .traces

### LINKED ISSUE #158: Feature request: CTRL+S to save .traces
It would be convenient to press CTRL+S and have the save traces dialog appear.  As a rough prototype, I added a key binding to the `PathManagerUI` `JScrollPane` which listens for CTRL+S when the window containing the scroll pane is in focus (i.e., when any component of `PathManagerUI` is selected), see https://github.com/morphonets/SNT/commit/3e79044d8cb8d1a541f2ba5b7bf46e4ce4eae15a

I would pull out the anonymous `AbstractAction` into it's own class, which could then be used by both `SNTUI` and `PathManagerUI` for saving traces. It seems to work well enough, but I worry that users may get confused since when the image is in focus, CTRL+S opens the image saving dialog instead. They would need to remember to click the Path Manager UI each time.

It would probably also make sense to add a listener to the main SNT dialog as well, @tferr what do you think?

### PR DESCRIPTION
**Pull request by carshadi**
Closes #158

### CODE REVIEW

**Comment by tferr** [comment]
@carshadi, thinking a bit more about this: what would be really beneficial is a mechanism to quickly save/restore  tracings from disk. I was not able to implement a full auto-save system, but added a couple of things to this PR that should streamline workflows:
- Ctrl+S now proposes a more sensible filename based on the image being traced (as opposed to always 'SNT_Data.traces'
- Ctrl+Shift+S now saves a timestamped Traces file without any prompt (this requires a file to be saved at least once)
- There is a new 'Restore from snapshot' command that offers a list of all the timestamped traces files, and reverts everything to the contents of the chosen time point
- I also _tried_ to improve the flag that keeps track of unchanged paths (while doing this I noticed a bunch of invasive operations that were being excluded from its logic
- I did not have time to test things in detail, could you please have a look?
Overall, this should make SNT safer to use, and more resilient to data loss!?

**Comment by tferr** [comment]
@carshadi , it seems I have to release a new SNT version soon. Do you have time to look at this soonish? If so, this could be included.

**Comment by tferr** [comment]
Oh, it is the colons in the time stamp. Windows does not seem to support it in filenames!?

**Comment by carshadi** [comment]
@tferr that fixed it. I tested it for a while and think this is good to merge!

**Pull request merged**
