### PR TITLE
update 4_bottleneck_distance.ipynb with new API

### PR DESCRIPTION
**Pull request by carshadi**
change ```getPersistenceDiagram()``` to ```getDiagram()```

### CODE REVIEW

**Comment by carshadi** [comment]
Also, do you think we should update this to use the persistence landscapes instead of bottleneck distance? There could be a few advantages:
* Show off the native persistent homology features of SNT
* Remove the dependency on gudhi (which can be a pain to install using conda)
* Shorten the amount of code, and retain the same clustering accuracy
* Much faster computation time

Thoughts?

**Comment by tferr** [comment]
Great idea. That would be great. I'll wait for it before merging!

**Comment by carshadi** [comment]
updated

**Comment by tferr** [comment]
Perfect! thanks!

**Pull request merged**
